export const CATEGORY = {
  recently: {
    id: "recently",
    style: { textDecoration: "underline" },
    name: { en: "Recently", vi: "Gần đây" },
  },
  available: {
    id: "available",
    showCount: true,
    style: { textDecoration: "underline" },
    name: { en: "Available", vi: "Có thể dùng" },
  },
  search: { id: "search", name: { en: "Search", vi: "Tìm kiếm" } },
  download: { id: "download", name: { en: "Download", vi: "Tải xuống" } },
  facebook: { id: "facebook", name: { en: "Facebook", vi: "Facebook" } },
  instagram: { id: "instagram", name: { en: "Instagram", vi: "Instagram" } },
  youtube: { id: "youtube", name: { en: "Youtube", vi: "Youtube" } },
  github: { id: "github", name: { en: "Github", vi: "Github" } },
  doutube: { id: "doutube", name: { en: "Doutu.be", vi: "Doutu.be" } },
  vimeo: { id: "vimeo", name: { en: "Vimeo", vi: "Vimeo" } },
  pdf: { id: "pdf", name: { en: "PDF", vi: "PDF" } },
  qrcode: { id: "qrcode", name: { en: "QR Code", vi: "QR Code" } },
  automation: {
    id: "automation",
    name: { en: "Automation", vi: "Tự động hoá" },
  },
  password: { id: "password", name: { en: "Password", vi: "Mật khẩu" } },
  unlock: { id: "unlock", name: { en: "Unlock", vi: "Mở khoá" } },
  webUI: { id: "webui", name: { en: "Web UI", vi: "Giao diện" } },
  more: { id: "more", name: { en: "More...", vi: "Khác..." } },
  recommend: {
    id: "recommend",
    style: { textDecoration: "underline" },
    name: { en: "Recommend", vi: "Khuyên dùng" },
  },
};
